yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"
